### ISSUE TITLE
Giving input

### ISSUE THREAD

**Issue by ravi-saini35** [rohitthapliyal2000/SIC-Assembler#1]
hello,
           I am not able to understand what input should give.
please explain.

**Comment by rohitthapliyal2000** [comment]
Hey Ravi, 
Move over to the directory **Sample**, it has a sample input and output file for your reference.

**Comment by ravi-saini35** [comment]
Yeah , but the Driver.cpp is not working properly. If it's working then pls send me some screenshots.
I really need the code.

**Comment by rohitthapliyal2000** [comment]
Sorry, but I don't remember any part of the code now.
Thanks.

**Comment by rohitthapliyal2000** [comment]
Maybe it will run with C++14:
g++ -std=c++14 Driver.cpp
